package ai.xdev.aisdlc.service;

import ai.xdev.aisdlc.domain.DomainTypes.MembershipRole;
import com.fasterxml.jackson.databind.JsonNode;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Authorizes provider and tool intent only. It never persists prompts, sends requests upstream, or executes a tool. */
@Service
public class RuntimeAiBrokerService {
  public record AuthorizationView(String decision, String reasonCode, UUID runtimeDecisionId, UUID budgetDecisionId) { public boolean allowed(){return "ALLOW".equals(decision);} }
  private final JdbcTemplate jdbc; private final ProjectAccessService access; private final RuntimeAiGovernanceService governance; private final BudgetEnforcementService budgets; private final AuditService audit;
  public RuntimeAiBrokerService(JdbcTemplate jdbc,ProjectAccessService access,RuntimeAiGovernanceService governance,BudgetEnforcementService budgets,AuditService audit){this.jdbc=jdbc;this.access=access;this.governance=governance;this.budgets=budgets;this.audit=audit;}
  @Transactional public void registerWorkload(UUID projectId,String actor,String subject,boolean active){var p=access.requireMembership(projectId,actor,MembershipRole.OWNER); bounded(subject,240);jdbc.update("insert into runtime_ai_workload_identities(id,project_id,workload_subject,active,created_by) values(?,?,?,?,?) on conflict(project_id,workload_subject) do update set active=excluded.active",UUID.randomUUID(),projectId,subject.trim(),active,actor);audit.append(p.getOrganizationId(),projectId,actor,"runtime_ai.workload_configured","runtime_ai_workload",sha256(subject),"{\"active\":"+active+"}");}
  @Transactional public void configureProvider(UUID projectId,String actor,String provider,String model,UUID bundleId,String endpointUri,String credentialReference,String mtlsReference,boolean requireMtls,int timeoutMs,int maxAttempts,boolean active){var p=access.requireMembership(projectId,actor,MembershipRole.OWNER);bounded(provider,160);bounded(model,240);bounded(credentialReference,240);if(requireMtls)bounded(mtlsReference,240);validateEndpoint(endpointUri);if(timeoutMs<100||timeoutMs>120000||maxAttempts<1||maxAttempts>3)throw new IllegalArgumentException("Invalid provider bounds");jdbc.update("insert into runtime_ai_provider_profiles(id,project_id,provider_name,model_name,policy_bundle_id,credential_reference,timeout_ms,max_attempts,active,created_by,endpoint_uri,require_mtls,mtls_reference) values(?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(project_id,provider_name,model_name) do update set policy_bundle_id=excluded.policy_bundle_id,credential_reference=excluded.credential_reference,timeout_ms=excluded.timeout_ms,max_attempts=excluded.max_attempts,active=excluded.active,endpoint_uri=excluded.endpoint_uri,require_mtls=excluded.require_mtls,mtls_reference=excluded.mtls_reference",UUID.randomUUID(),projectId,provider.trim(),model.trim(),bundleId,credentialReference.trim(),timeoutMs,maxAttempts,active,actor,endpointUri.trim(),requireMtls,requireMtls?mtlsReference.trim():null);audit.append(p.getOrganizationId(),projectId,actor,"runtime_ai.provider_configured","runtime_ai_provider",sha256(provider+"|"+model),"{\"active\":"+active+",\"endpointSha256\":\""+sha256(endpointUri.trim())+"\",\"requireMtls\":"+requireMtls+"}");}
  @Transactional public void configureTool(UUID projectId,String actor,String tool,UUID bundleId,String impact,boolean requiresApproval,boolean active){var p=access.requireMembership(projectId,actor,MembershipRole.OWNER);bounded(tool,160);if(!impact.matches("READ_ONLY|MUTATING|HIGH_IMPACT"))throw new IllegalArgumentException("Invalid impact");jdbc.update("insert into runtime_ai_tool_capabilities(id,project_id,tool_name,policy_bundle_id,impact_level,requires_approval,active,created_by) values(?,?,?,?,?,?,?,?) on conflict(project_id,tool_name) do update set policy_bundle_id=excluded.policy_bundle_id,impact_level=excluded.impact_level,requires_approval=excluded.requires_approval,active=excluded.active",UUID.randomUUID(),projectId,tool.trim(),bundleId,impact,requiresApproval,active,actor);audit.append(p.getOrganizationId(),projectId,actor,"runtime_ai.tool_configured","runtime_ai_tool",sha256(tool),"{\"active\":"+active+"}");}
  @Transactional public AuthorizationView preflight(UUID projectId,String subject,UUID agentSessionId,String provider,String model,String fingerprint,JsonNode context,boolean dryRun){requireWorkload(projectId,subject); UUID bundle;try{bundle=jdbc.queryForObject("select policy_bundle_id from runtime_ai_provider_profiles where project_id=? and provider_name=? and model_name=? and active=true",UUID.class,projectId,provider,model);}catch(org.springframework.dao.EmptyResultDataAccessException e){return new AuthorizationView("DENY","MODEL_OR_PROVIDER_NOT_ALLOWLISTED",null,null);} var budget=budgets.evaluateForRuntime(projectId,subject);if(!budget.allowed())return new AuthorizationView("DENY","BUDGET_"+budget.reasonCode(),null,budget.id());var d=governance.decideForRuntimeWorkload(projectId,subject,agentSessionId,bundle,"PRE_FLIGHT",fingerprint,context,dryRun);return new AuthorizationView(d.decision(),d.reasonCode(),d.id(),budget.id());}
  @Transactional public AuthorizationView authorizeTool(UUID projectId,String subject,UUID agentSessionId,String tool,String fingerprint,JsonNode context,UUID approvalRequestId,boolean dryRun){requireWorkload(projectId,subject);java.util.Map<String,Object> row;try{row=jdbc.queryForMap("select policy_bundle_id,impact_level,requires_approval from runtime_ai_tool_capabilities where project_id=? and tool_name=? and active=true",projectId,tool);}catch(org.springframework.dao.EmptyResultDataAccessException e){return new AuthorizationView("DENY","TOOL_NOT_ALLOWLISTED",null,null);}boolean high="HIGH_IMPACT".equals(row.get("impact_level"))||Boolean.TRUE.equals(row.get("requires_approval"));if(high&&(approvalRequestId==null||!Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from approval_requests where id=? and project_id=? and approval_status='APPROVED')",Boolean.class,approvalRequestId,projectId))))return new AuthorizationView("DENY","HUMAN_APPROVAL_REQUIRED",null,null);var d=governance.decideForRuntimeWorkload(projectId,subject,agentSessionId,(UUID)row.get("policy_bundle_id"),"TOOL_CALL",fingerprint,context,dryRun);return new AuthorizationView(d.decision(),d.reasonCode(),d.id(),null);}
  private void requireWorkload(UUID projectId,String subject){bounded(subject,240);Boolean active=jdbc.queryForObject("select exists(select 1 from runtime_ai_workload_identities where project_id=? and workload_subject=? and active=true)",Boolean.class,projectId,subject);if(!Boolean.TRUE.equals(active))throw new IllegalArgumentException("Unregistered runtime workload");} private static void bounded(String value,int max){if(value==null||value.isBlank()||value.trim().length()>max)throw new IllegalArgumentException("Required bounded value missing");} private static void validateEndpoint(String value){try{java.net.URI uri=java.net.URI.create(value);if(!"https".equalsIgnoreCase(uri.getScheme())||uri.getHost()==null||uri.getRawUserInfo()!=null||uri.getRawQuery()!=null||uri.getRawFragment()!=null)throw new IllegalArgumentException("Invalid provider endpoint");}catch(RuntimeException e){throw new IllegalArgumentException("Invalid provider endpoint",e);}} private static String sha256(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
