-- P3.2: back-testing evidence for the inference cost forecast.
--
-- The prototype stored a prediction and a fixed +/-20% band with no record of whether that band had ever held. A
-- forecast without back-test evidence cannot be distinguished from a guess after the fact, which is the specific
-- failure the cost-governance design calls out: an unreliable projection that looks identical to a reliable one.
--
-- These columns are nullable because a forecast may legitimately return INSUFFICIENT_DATA, and a fabricated zero
-- would read as a perfect back-test rather than an absent one.
alter table inference_cost_forecasts add column observed_days integer;
alter table inference_cost_forecasts add column backtest_folds integer;
alter table inference_cost_forecasts add column backtest_wape numeric(9,4);
alter table inference_cost_forecasts add column backtest_median_abs_error_minor bigint;
alter table inference_cost_forecasts add column backtest_interval_coverage numeric(5,4);
alter table inference_cost_forecasts add column explanation text;

-- Rows written by TRAILING_28D_DAILY_MEAN_V1 keep their values and stay explicitly unevaluated. Backfilling a
-- coverage figure for a method that never computed one would invent evidence.
update inference_cost_forecasts
   set explanation = 'Generated by TRAILING_28D_DAILY_MEAN_V1 before back-testing existed; no coverage evidence.'
 where explanation is null;

comment on column inference_cost_forecasts.backtest_interval_coverage is
  'Fraction of rolling-origin back-test days whose actual cost fell inside the predicted interval. Below 0.80 the forecast status is LOW_CONFIDENCE and must not drive an automated cost-control recommendation.';
